name: Pull Request Tests

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'app/yarn.lock'

      - name: Install dependencies
        run: cd app && yarn install --frozen-lockfile
        env:
          DATABASE_URL: mysql://goofyuser:goofypassword@localhost:3306/goofytrack

      - name: Lint code
        run: cd app && yarn lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: 'app/yarn.lock'

      - name: Install dependencies
        run: cd app && yarn install --frozen-lockfile
        env:
          DATABASE_URL: postgresql://neondb_owner:npg_HjtCh9gsyAx6@ep-little-glade-a4mcfgg1-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require



      - name: Run tests
        run: cd app && yarn test
        env:
          DATABASE_URL: postgresql://neondb_owner:npg_HjtCh9gsyAx6@ep-little-glade-a4mcfgg1-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'app/yarn.lock'

      - name: Install dependencies
        run: cd app && yarn install --frozen-lockfile
        env:
          DATABASE_URL: postgresql://neondb_owner:npg_HjtCh9gsyAx6@ep-little-glade-a4mcfgg1-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require

      - name: Build application
        run: cd app && yarn build
